# Generated by Django 4.1.7 on 2023-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecu', models.CharField(max_length=40, unique=True)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('job', models.CharField(max_length=50)),
                ('rwork', models.CharField(max_length=40)),
                ('pnum', models.IntegerField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Add', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('usernm', models.CharField(max_length=30, unique=True)),
                ('userpw', models.CharField(max_length=40)),
                ('slink', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
