# Generated by Django 4.1.7 on 2023-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_spd_pnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spd',
            old_name='job',
            new_name='jb',
        ),
        migrations.AlterField(
            model_name='spd',
            name='status',
            field=models.CharField(default='WL', max_length=3, null=True),
        ),
    ]
