# Generated by Django 4.1.7 on 2023-02-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_job_spd_jb_alter_spd_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spd',
            old_name='jb',
            new_name='job',
        ),
    ]
