# Generated by Django 4.1.7 on 2023-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_jb_spd_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spd',
            name='job',
            field=models.CharField(max_length=10),
        ),
    ]
