# Generated by Django 4.1.7 on 2023-02-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_spd_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHTOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='USINF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('pnum', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('usernm', models.CharField(max_length=30, unique=True)),
                ('userpW', models.CharField(max_length=40)),
            ],
        ),
    ]
