# Generated by Django 4.1.7 on 2023-02-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_userpw_usinf_userpw'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHTGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picmg', models.ImageField(upload_to='PHTGO/')),
                ('slink', models.CharField(max_length=40)),
                ('tpric', models.CharField(max_length=10)),
                ('Opric', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=30)),
                ('pid', models.CharField(max_length=40)),
            ],
        ),
    ]
