# Generated by Django 4.1.7 on 2023-02-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_phtgo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phtgo',
            old_name='Opric',
            new_name='opric',
        ),
    ]
