# Generated by Django 4.1.7 on 2023-02-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_usinf_prv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phtgo',
            name='picmg',
            field=models.ImageField(null=True, upload_to='PHTGO/'),
        ),
    ]
