# Generated by Django 4.1.7 on 2023-02-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_phtgo_picmg'),
    ]

    operations = [
        migrations.AddField(
            model_name='phtgo',
            name='cicmg',
            field=models.ImageField(default=None, null=True, upload_to='PHTGO/'),
        ),
    ]
