# Generated by Django 4.1.7 on 2023-02-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_phtgo_cicmg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CABO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=40)),
                ('cimg', models.ImageField(upload_to='CABO/')),
                ('carnm', models.CharField(max_length=60)),
                ('carmdl', models.CharField(max_length=60)),
                ('stcp', models.CharField(max_length=60)),
                ('tpric', models.CharField(max_length=60)),
            ],
        ),
    ]
