# Generated by Django 4.1.7 on 2023-02-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cabo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHTGOBooking',
            fields=[
                ('bno', models.IntegerField(primary_key=True, serialize=False)),
                ('bdate', models.DateField()),
                ('custid', models.IntegerField()),
                ('custname', models.CharField(max_length=40)),
                ('srvid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('serv', models.IntegerField()),
                ('rdate', models.DateField()),
                ('rtime', models.CharField(max_length=30)),
                ('amtpaid', models.IntegerField(default='0')),
                ('rstat', models.CharField(default='NEW REQ', max_length=20)),
                ('pstat', models.CharField(default='NOT PAID', max_length=20)),
                ('cardno', models.IntegerField()),
            ],
        ),
    ]
