# Generated by Django 4.1.7 on 2023-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_phtgobooking_bdate_alter_phtgobooking_cardno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabo',
            name='bookingch',
            field=models.IntegerField(default=2000),
        ),
    ]
