# Generated by Django 4.1.7 on 2023-02-27 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_cabo_bookingch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CABOBooking',
            fields=[
                ('bno', models.IntegerField(primary_key=True, serialize=False)),
                ('bdate', models.DateField(default=datetime.date.today)),
                ('custid', models.IntegerField()),
                ('custname', models.CharField(max_length=40)),
                ('srvid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('serv', models.CharField(max_length=40)),
                ('carname', models.CharField(max_length=40)),
                ('carmodel', models.CharField(max_length=40)),
                ('packid', models.IntegerField()),
                ('rdate', models.DateField()),
                ('amtpaid', models.IntegerField(default='0')),
                ('rstat', models.CharField(default='NEW REQ', max_length=20)),
                ('pstat', models.CharField(default='NOT PAID', max_length=20)),
                ('cardno', models.CharField(default='0', max_length=15)),
            ],
        ),
    ]
