# Generated by Django 4.1.7 on 2023-02-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_cabobooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabobooking',
            name='rtime',
            field=models.CharField(default='12:00AM', max_length=30),
        ),
    ]
